### PR TITLE
Some improvment made

### PR DESCRIPTION
**Pull request by dksmith328**
Hey Abderrahim -

Here are some improvements. Let me know what you think. I have more to make but thought we could use this as a "check-in".

-Daniel

### CODE REVIEW

**Comment by bacloud14** [comment]
This is just fantastic ! great design I like it a lot.
Responsiveness, smooth gradient colors: background, buttons, header and footer.

Just a note, on toggle dark mode, Could please change the background color to something darker? or do you feel the same color can go for dark mode ?

Also I noticed a full change on background color (gradient) when scrolling just after weather cards.

Also please add a reference on footer.

Tomorrow I will push my changes, you would see few improvements (but a lot of bugs resolved).

Thanks again !

**Comment by bacloud14** [comment]
G map key is public now, but don't bother, I will keep it that

**Comment by bacloud14** [comment]
I think I have one other preference, between weather cards and photos album, probably we need some space, or a title for each section.

**Comment by dksmith328** [comment]
Yes I agree. 
I am planning to -

Change the spacing between the weather cards and the gallery
Make the entire app more responsive to size changes
Improve the gradient for the background
Make dark mode improvements 
Add a reference on footer. 

I will wait until you give me the okay 

-Daniel

**Comment by bacloud14** [comment]
Ok, great, count on me tomorrow.

Le lun. 1 févr. 2021 à 8:08 PM, dksmith328 <notifications@github.com> a
écrit :

**Pull request merged**
